//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.3-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.09.26 at 01:00:47 EDT 
//


package edu.mit.coeus.utils.xml.bean.subcontractingReports;


/**
 * Java content class for anonymous complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/Subcontracting_294_295%20printing/schema/subcontractingReports.xsd line 37)
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ReportNumber" minOccurs="0">
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="294"/>
 *             &lt;enumeration value="295"/>
 *           &lt;/restriction>
 *         &lt;/element>
 *         &lt;element name="DateSubmitted" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="CompanyInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}NameAndAddressType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ContractorIDNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReportingPeriod">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="isMarchReport" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="isSeptReport" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="ReportType">
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="Regular"/>
 *                       &lt;enumeration value="Final"/>
 *                       &lt;enumeration value="Revised"/>
 *                     &lt;/restriction>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="FiscalYearReportStart" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FiscalYearReportEnd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ContractorType">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="isPrime" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="PrimeContractNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="isSub" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="SubContractNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PlanType" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TypeofPlan">
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="Individual"/>
 *                       &lt;enumeration value="Commercial"/>
 *                     &lt;/restriction>
 *                   &lt;/element>
 *                   &lt;element name="Percentage" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ContractorProducts" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ALine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="BLine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="IncludeIndirectCosts" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="SubcontractReportPage" type="{}SubcontractReportPageType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AdministeringOfficial">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PhoneAreaCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="PhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CEO" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="OtherSponsors" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface SubcontractReportsType {


    /**
     * Gets the value of the fiscalYearReportStart property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getFiscalYearReportStart();

    /**
     * Sets the value of the fiscalYearReportStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setFiscalYearReportStart(java.lang.String value);

    /**
     * Gets the value of the reportingPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link edu.mit.coeus.utils.xml.bean.subcontractingReports.SubcontractReportsType.ReportingPeriodType}
     */
    edu.mit.coeus.utils.xml.bean.subcontractingReports.SubcontractReportsType.ReportingPeriodType getReportingPeriod();

    /**
     * Sets the value of the reportingPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.mit.coeus.utils.xml.bean.subcontractingReports.SubcontractReportsType.ReportingPeriodType}
     */
    void setReportingPeriod(edu.mit.coeus.utils.xml.bean.subcontractingReports.SubcontractReportsType.ReportingPeriodType value);

    /**
     * Gets the value of the contractorIDNumber property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getContractorIDNumber();

    /**
     * Sets the value of the contractorIDNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setContractorIDNumber(java.lang.String value);

    /**
     * Gets the value of the fiscalYearReportEnd property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getFiscalYearReportEnd();

    /**
     * Sets the value of the fiscalYearReportEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setFiscalYearReportEnd(java.lang.String value);

    /**
     * Gets the value of the contractorType property.
     * 
     * @return
     *     possible object is
     *     {@link edu.mit.coeus.utils.xml.bean.subcontractingReports.SubcontractReportsType.ContractorTypeType}
     */
    edu.mit.coeus.utils.xml.bean.subcontractingReports.SubcontractReportsType.ContractorTypeType getContractorType();

    /**
     * Sets the value of the contractorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.mit.coeus.utils.xml.bean.subcontractingReports.SubcontractReportsType.ContractorTypeType}
     */
    void setContractorType(edu.mit.coeus.utils.xml.bean.subcontractingReports.SubcontractReportsType.ContractorTypeType value);

    /**
     * Gets the value of the contractorProducts property.
     * 
     * @return
     *     possible object is
     *     {@link edu.mit.coeus.utils.xml.bean.subcontractingReports.SubcontractReportsType.ContractorProductsType}
     */
    edu.mit.coeus.utils.xml.bean.subcontractingReports.SubcontractReportsType.ContractorProductsType getContractorProducts();

    /**
     * Sets the value of the contractorProducts property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.mit.coeus.utils.xml.bean.subcontractingReports.SubcontractReportsType.ContractorProductsType}
     */
    void setContractorProducts(edu.mit.coeus.utils.xml.bean.subcontractingReports.SubcontractReportsType.ContractorProductsType value);

    /**
     * Gets the value of the OtherSponsors property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the OtherSponsors property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherSponsors().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link java.lang.String}
     * 
     */
    java.util.List getOtherSponsors();

    /**
     * Gets the value of the reportNumber property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getReportNumber();

    /**
     * Sets the value of the reportNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setReportNumber(java.lang.String value);

    /**
     * Gets the value of the includeIndirectCosts property.
     * 
     */
    boolean isIncludeIndirectCosts();

    /**
     * Sets the value of the includeIndirectCosts property.
     * 
     */
    void setIncludeIndirectCosts(boolean value);

    /**
     * Gets the value of the companyInfo property.
     * 
     * @return
     *     possible object is
     *     {@link edu.mit.coeus.utils.xml.bean.subcontractingReports.SubcontractReportsType.CompanyInfoType}
     */
    edu.mit.coeus.utils.xml.bean.subcontractingReports.SubcontractReportsType.CompanyInfoType getCompanyInfo();

    /**
     * Sets the value of the companyInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.mit.coeus.utils.xml.bean.subcontractingReports.SubcontractReportsType.CompanyInfoType}
     */
    void setCompanyInfo(edu.mit.coeus.utils.xml.bean.subcontractingReports.SubcontractReportsType.CompanyInfoType value);

    /**
     * Gets the value of the SubcontractReportPage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the SubcontractReportPage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubcontractReportPage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link edu.mit.coeus.utils.xml.bean.subcontractingReports.SubcontractReportPageType}
     * 
     */
    java.util.List getSubcontractReportPage();

    /**
     * Gets the value of the planType property.
     * 
     * @return
     *     possible object is
     *     {@link edu.mit.coeus.utils.xml.bean.subcontractingReports.SubcontractReportsType.PlanTypeType}
     */
    edu.mit.coeus.utils.xml.bean.subcontractingReports.SubcontractReportsType.PlanTypeType getPlanType();

    /**
     * Sets the value of the planType property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.mit.coeus.utils.xml.bean.subcontractingReports.SubcontractReportsType.PlanTypeType}
     */
    void setPlanType(edu.mit.coeus.utils.xml.bean.subcontractingReports.SubcontractReportsType.PlanTypeType value);

    /**
     * Gets the value of the administeringOfficial property.
     * 
     * @return
     *     possible object is
     *     {@link edu.mit.coeus.utils.xml.bean.subcontractingReports.SubcontractReportsType.AdministeringOfficialType}
     */
    edu.mit.coeus.utils.xml.bean.subcontractingReports.SubcontractReportsType.AdministeringOfficialType getAdministeringOfficial();

    /**
     * Sets the value of the administeringOfficial property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.mit.coeus.utils.xml.bean.subcontractingReports.SubcontractReportsType.AdministeringOfficialType}
     */
    void setAdministeringOfficial(edu.mit.coeus.utils.xml.bean.subcontractingReports.SubcontractReportsType.AdministeringOfficialType value);

    /**
     * Gets the value of the ceo property.
     * 
     * @return
     *     possible object is
     *     {@link edu.mit.coeus.utils.xml.bean.subcontractingReports.SubcontractReportsType.CEOType}
     */
    edu.mit.coeus.utils.xml.bean.subcontractingReports.SubcontractReportsType.CEOType getCEO();

    /**
     * Sets the value of the ceo property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.mit.coeus.utils.xml.bean.subcontractingReports.SubcontractReportsType.CEOType}
     */
    void setCEO(edu.mit.coeus.utils.xml.bean.subcontractingReports.SubcontractReportsType.CEOType value);

    /**
     * Gets the value of the dateSubmitted property.
     * 
     * @return
     *     possible object is
     *     {@link java.util.Calendar}
     */
    java.util.Calendar getDateSubmitted();

    /**
     * Sets the value of the dateSubmitted property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.util.Calendar}
     */
    void setDateSubmitted(java.util.Calendar value);


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/Subcontracting_294_295%20printing/schema/subcontractingReports.xsd line 111)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PhoneAreaCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="PhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface AdministeringOfficialType {


        /**
         * Gets the value of the phoneNumber property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getPhoneNumber();

        /**
         * Sets the value of the phoneNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setPhoneNumber(java.lang.String value);

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getTitle();

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setTitle(java.lang.String value);

        /**
         * Gets the value of the phoneAreaCode property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getPhoneAreaCode();

        /**
         * Sets the value of the phoneAreaCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setPhoneAreaCode(java.lang.String value);

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getName();

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setName(java.lang.String value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/Subcontracting_294_295%20printing/schema/subcontractingReports.xsd line 121)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface CEOType {


        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getTitle();

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setTitle(java.lang.String value);

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getName();

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setName(java.lang.String value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/Subcontracting_294_295%20printing/schema/subcontractingReports.xsd line 49)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}NameAndAddressType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface CompanyInfoType {


        /**
         * Gets the value of the nameAndAddressType property.
         * 
         * @return
         *     possible object is
         *     {@link edu.mit.coeus.utils.xml.bean.subcontractingReports.NameAndAddressTypeType}
         *     {@link edu.mit.coeus.utils.xml.bean.subcontractingReports.NameAndAddressType}
         */
        edu.mit.coeus.utils.xml.bean.subcontractingReports.NameAndAddressTypeType getNameAndAddressType();

        /**
         * Sets the value of the nameAndAddressType property.
         * 
         * @param value
         *     allowed object is
         *     {@link edu.mit.coeus.utils.xml.bean.subcontractingReports.NameAndAddressTypeType}
         *     {@link edu.mit.coeus.utils.xml.bean.subcontractingReports.NameAndAddressType}
         */
        void setNameAndAddressType(edu.mit.coeus.utils.xml.bean.subcontractingReports.NameAndAddressTypeType value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/Subcontracting_294_295%20printing/schema/subcontractingReports.xsd line 101)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ALine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="BLine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface ContractorProductsType {


        /**
         * Gets the value of the aLine property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getALine();

        /**
         * Sets the value of the aLine property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setALine(java.lang.String value);

        /**
         * Gets the value of the bLine property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getBLine();

        /**
         * Sets the value of the bLine property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setBLine(java.lang.String value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/Subcontracting_294_295%20printing/schema/subcontractingReports.xsd line 76)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="isPrime" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="PrimeContractNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="isSub" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="SubContractNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface ContractorTypeType {


        /**
         * Gets the value of the primeContractNumber property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getPrimeContractNumber();

        /**
         * Sets the value of the primeContractNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setPrimeContractNumber(java.lang.String value);

        /**
         * Gets the value of the isSub property.
         * 
         */
        boolean isIsSub();

        /**
         * Sets the value of the isSub property.
         * 
         */
        void setIsSub(boolean value);

        /**
         * Gets the value of the subContractNumber property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getSubContractNumber();

        /**
         * Sets the value of the subContractNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setSubContractNumber(java.lang.String value);

        /**
         * Gets the value of the isPrime property.
         * 
         */
        boolean isIsPrime();

        /**
         * Sets the value of the isPrime property.
         * 
         */
        void setIsPrime(boolean value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/Subcontracting_294_295%20printing/schema/subcontractingReports.xsd line 86)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TypeofPlan">
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="Individual"/>
     *             &lt;enumeration value="Commercial"/>
     *           &lt;/restriction>
     *         &lt;/element>
     *         &lt;element name="Percentage" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface PlanTypeType {


        /**
         * Gets the value of the typeofPlan property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getTypeofPlan();

        /**
         * Sets the value of the typeofPlan property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setTypeofPlan(java.lang.String value);

        /**
         * Gets the value of the percentage property.
         * 
         * @return
         *     possible object is
         *     {@link java.math.BigDecimal}
         */
        java.math.BigDecimal getPercentage();

        /**
         * Sets the value of the percentage property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.math.BigDecimal}
         */
        void setPercentage(java.math.BigDecimal value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/Subcontracting_294_295%20printing/schema/subcontractingReports.xsd line 57)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="isMarchReport" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="isSeptReport" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="ReportType">
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="Regular"/>
     *             &lt;enumeration value="Final"/>
     *             &lt;enumeration value="Revised"/>
     *           &lt;/restriction>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface ReportingPeriodType {


        /**
         * Gets the value of the isSeptReport property.
         * 
         */
        boolean isIsSeptReport();

        /**
         * Sets the value of the isSeptReport property.
         * 
         */
        void setIsSeptReport(boolean value);

        /**
         * Gets the value of the reportType property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getReportType();

        /**
         * Sets the value of the reportType property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setReportType(java.lang.String value);

        /**
         * Gets the value of the isMarchReport property.
         * 
         */
        boolean isIsMarchReport();

        /**
         * Sets the value of the isMarchReport property.
         * 
         */
        void setIsMarchReport(boolean value);

    }

}
