//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.25 at 01:45:05 CDT 
//


package gov.grants.apply.forms.phs398_researchtrainingprogramplan_4_0_v4.impl;

public class JAXBVersion {

    public final static java.lang.String version = "1.0.4";

}
