CREATE OR REPLACE procedure COEUS.dw_get_a_apprvd_sub_for_seq
   (  AW_MIT_AWARD_NUMBER IN OSP$AWARD_APPROVED_SUBCONTRACT.MIT_AWARD_NUMBER%TYPE,
      AW_SEQUENCE_NUMBER IN OSP$AWARD_APPROVED_SUBCONTRACT.SEQUENCE_NUMBER%TYPE,
      cur_generic IN OUT result_sets.cur_generic) is

begin

open cur_generic for
    /* JM 7-30-2013 added organization Id; 6-22-2016 updated for location type */
    SELECT s.*, l.location_type_desc
    FROM OSP$AWARD_APPROVED_SUBCONTRACT s, OSP$LOCATION_TYPE l
    WHERE s.MIT_AWARD_NUMBER = AW_MIT_AWARD_NUMBER
    AND s.LOCATION_TYPE_CODE = l.LOCATION_TYPE_CODE
    AND s.SEQUENCE_NUMBER IN  ( 
        SELECT MAX(A.SEQUENCE_NUMBER)
        FROM OSP$AWARD_APPROVED_SUBCONTRACT A
        WHERE A.MIT_AWARD_NUMBER = s.MIT_AWARD_NUMBER 
        and A.SEQUENCE_NUMBER = AW_SEQUENCE_NUMBER);

end;
/
