CREATE OR REPLACE PROCEDURE COEUS.dw_update_a_apprvd_subcontract (
    AV_MIT_AWARD_NUMBER  IN  OSP$AWARD_APPROVED_SUBCONTRACT.MIT_AWARD_NUMBER%TYPE := NULL,
    AV_SEQUENCE_NUMBER  IN  OSP$AWARD_APPROVED_SUBCONTRACT.SEQUENCE_NUMBER%TYPE := NULL,
    AV_SUBCONTRACTOR_NAME  IN  OSP$AWARD_APPROVED_SUBCONTRACT.SUBCONTRACTOR_NAME%TYPE := NULL,
    AV_LOCATION_TYPE_CODE  IN  OSP$AWARD_APPROVED_SUBCONTRACT.LOCATION_TYPE_CODE%TYPE := NULL, 
    AV_ORGANIZATION_ID  IN  OSP$AWARD_APPROVED_SUBCONTRACT.ORGANIZATION_ID%TYPE := NULL,
    AV_AMOUNT  IN  OSP$AWARD_APPROVED_SUBCONTRACT.AMOUNT%TYPE := NULL,
    AV_UPDATE_TIMESTAMP  IN  OSP$AWARD_APPROVED_SUBCONTRACT.UPDATE_TIMESTAMP%TYPE := NULL,
    AV_UPDATE_USER  IN  OSP$AWARD_APPROVED_SUBCONTRACT.UPDATE_USER%TYPE := NULL,

    AW_MIT_AWARD_NUMBER  IN  OSP$AWARD_APPROVED_SUBCONTRACT.MIT_AWARD_NUMBER%TYPE := NULL,
    AW_SEQUENCE_NUMBER  IN  OSP$AWARD_APPROVED_SUBCONTRACT.SEQUENCE_NUMBER%TYPE := NULL,
    AW_SUBCONTRACTOR_NAME  IN  OSP$AWARD_APPROVED_SUBCONTRACT.SUBCONTRACTOR_NAME%TYPE := NULL,
    AW_LOCATION_TYPE_CODE  IN  OSP$AWARD_APPROVED_SUBCONTRACT.LOCATION_TYPE_CODE%TYPE := NULL,
    AW_ORGANIZATION_ID  IN  OSP$AWARD_APPROVED_SUBCONTRACT.ORGANIZATION_ID%TYPE := NULL,
    AW_UPDATE_TIMESTAMP  IN  OSP$AWARD_APPROVED_SUBCONTRACT.UPDATE_TIMESTAMP%TYPE := NULL,

    AC_TYPE  IN VARCHAR2 )

IS
    -- JM 8-23-2013 always going to insert and delete, never update; added organization ID

    --data_changed             EXCEPTION;

BEGIN

    IF AC_TYPE = 'I' THEN
        /* JM 8-23-2013 delete before insert to avoid primary key issues */
        DELETE FROM OSP$AWARD_APPROVED_SUBCONTRACT
        WHERE MIT_AWARD_NUMBER = AW_MIT_AWARD_NUMBER
        AND SEQUENCE_NUMBER = AW_SEQUENCE_NUMBER
        AND SUBCONTRACTOR_NAME = AW_SUBCONTRACTOR_NAME
        AND LOCATION_TYPE_CODE = AW_LOCATION_TYPE_CODE
        AND ORGANIZATION_ID = AW_ORGANIZATION_ID;

        INSERT INTO OSP$AWARD_APPROVED_SUBCONTRACT (
            MIT_AWARD_NUMBER,
            SEQUENCE_NUMBER,
            SUBCONTRACTOR_NAME,
            LOCATION_TYPE_CODE,
            ORGANIZATION_ID,
            AMOUNT,
            UPDATE_TIMESTAMP,
            UPDATE_USER )
        VALUES (
            AV_MIT_AWARD_NUMBER,
            AV_SEQUENCE_NUMBER,
            AV_SUBCONTRACTOR_NAME,
            AV_LOCATION_TYPE_CODE,
            AV_ORGANIZATION_ID,
            AV_AMOUNT,
            AV_UPDATE_TIMESTAMP,
            AV_UPDATE_USER );

    ELSIF AC_TYPE = 'U' THEN

        /* JM 8-23-2013 delete / insert rather than straight update 
        DELETE FROM OSP$AWARD_APPROVED_SUBCONTRACT
        WHERE MIT_AWARD_NUMBER = AW_MIT_AWARD_NUMBER
        AND SEQUENCE_NUMBER = AW_SEQUENCE_NUMBER
        AND LOCATION_TYPE_CODE = AW_LOCATION_TYPE_CODE
        AND SUBCONTRACTOR_NAME = AW_SUBCONTRACTOR_NAME
        AND ORGANIZATION_ID = AW_ORGANIZATION_ID;

        INSERT INTO OSP$AWARD_APPROVED_SUBCONTRACT (
            MIT_AWARD_NUMBER,
            SEQUENCE_NUMBER,
            SUBCONTRACTOR_NAME,
            LOCATION_TYPE_CODE,
            ORGANIZATION_ID,
            AMOUNT,
            UPDATE_TIMESTAMP,
            UPDATE_USER )
        VALUES (
            AV_MIT_AWARD_NUMBER,
            AV_SEQUENCE_NUMBER,
            AV_SUBCONTRACTOR_NAME,
            AV_LOCATION_TYPE_CODE,
            AV_ORGANIZATION_ID,
            AV_AMOUNT,
            AV_UPDATE_TIMESTAMP,
            AV_UPDATE_USER );
        */
        
        UPDATE OSP$AWARD_APPROVED_SUBCONTRACT
        SET MIT_AWARD_NUMBER = AV_MIT_AWARD_NUMBER,
            SEQUENCE_NUMBER = AV_SEQUENCE_NUMBER,
            SUBCONTRACTOR_NAME = AV_SUBCONTRACTOR_NAME,
            LOCATION_TYPE_CODE = AV_LOCATION_TYPE_CODE,
            ORGANIZATION_ID = AV_ORGANIZATION_ID,
            AMOUNT = AV_AMOUNT,
            UPDATE_TIMESTAMP = AV_UPDATE_TIMESTAMP,
            UPDATE_USER = AV_UPDATE_USER
        WHERE MIT_AWARD_NUMBER = AW_MIT_AWARD_NUMBER
        AND SEQUENCE_NUMBER = AW_SEQUENCE_NUMBER
        AND LOCATION_TYPE_CODE = AW_LOCATION_TYPE_CODE
        AND SUBCONTRACTOR_NAME = AW_SUBCONTRACTOR_NAME
        AND ORGANIZATION_ID = AW_ORGANIZATION_ID;
        
    ELSIF AC_TYPE = 'D' THEN

        DELETE FROM OSP$AWARD_APPROVED_SUBCONTRACT
        WHERE MIT_AWARD_NUMBER = AW_MIT_AWARD_NUMBER
        AND SEQUENCE_NUMBER = AW_SEQUENCE_NUMBER
        AND LOCATION_TYPE_CODE = AW_LOCATION_TYPE_CODE
        AND SUBCONTRACTOR_NAME = AW_SUBCONTRACTOR_NAME
        AND ORGANIZATION_ID = AW_ORGANIZATION_ID;

    END IF;

--EXCEPTION
--    WHEN data_changed THEN
--        raise_application_error(-20100, 'Data changed between retrieve and update');
COMMIT;
END;
/
