alter table OSP$PROPOSAL_APPROVED_SUB
add LOCATION_TYPE_CODE  NUMBER(3);

alter table OSP$PROPOSAL_APPROVED_SUB
add constraint fk_prop_appr_sub_location_type FOREIGN KEY (location_type_code)
references OSP$LOCATION_TYPE (LOCATION_TYPE_CODE);

alter table OSP$PROPOSAL_APPROVED_SUB
drop constraint PK_PROPOSAL_APPROVED_SUB;

update OSP$PROPOSAL_APPROVED_SUB
set location_type_code = 3;

alter table OSP$PROPOSAL_APPROVED_SUB
add constraint PK_PROPOSAL_APPROVED_SUB PRIMARY KEY (PROPOSAL_NUMBER,SEQUENCE_NUMBER,SUBCONTRACTOR_NAME,LOCATION_TYPE_CODE);


alter table OSP$AWARD_APPROVED_SUBCONTRACT
add LOCATION_TYPE_CODE  NUMBER(3);

alter table OSP$AWARD_APPROVED_SUBCONTRACT
add constraint fk_awd_appr_sub_location_type FOREIGN KEY (location_type_code)
references OSP$LOCATION_TYPE (LOCATION_TYPE_CODE);

alter table OSP$AWARD_APPROVED_SUBCONTRACT
drop constraint PK_AWARD_APPROVED_SUBCONTRACT;

drop index PK_AWARD_APPROVED_SUBCONTRACT;

update OSP$AWARD_APPROVED_SUBCONTRACT
set location_type_code = 3;

alter table OSP$AWARD_APPROVED_SUBCONTRACT
add constraint PK_AWARD_APPROVED_SUBCONTRACT PRIMARY KEY (MIT_AWARD_NUMBER,SEQUENCE_NUMBER,SUBCONTRACTOR_NAME,LOCATION_TYPE_CODE);

commit;