CREATE OR REPLACE procedure COEUS.VU_GET_PROPOSAL_APPROVED_SUBS (
    AW_PROPOSAL_NUMBER IN OSP$PROPOSAL_APPROVED_SUB.PROPOSAL_NUMBER%TYPE,
    cur_generic IN OUT result_sets.cur_generic) 
    
is

begin

open cur_generic for

    SELECT s.*, l.location_type_desc
    FROM OSP$PROPOSAL_APPROVED_SUB s, OSP$LOCATION_TYPE l
    WHERE s.PROPOSAL_NUMBER = AW_PROPOSAL_NUMBER
    AND s.LOCATION_TYPE_CODE = l.LOCATION_TYPE_CODE
    AND s.SEQUENCE_NUMBER IN ( 
        SELECT MAX(A.SEQUENCE_NUMBER)
        FROM   OSP$PROPOSAL_APPROVED_SUB A
        WHERE A.PROPOSAL_NUMBER = s.PROPOSAL_NUMBER
    );

end;
/
