CREATE OR REPLACE PROCEDURE COEUS.VU_GET_LOCATION_TYPES (
    CUR_LOCATION IN OUT result_sets.cur_generic
)
IS

BEGIN
     OPEN CUR_LOCATION FOR
           SELECT LOCATION_TYPE_CODE,
                  LOCATION_TYPE_DESC
          FROM OSP$LOCATION_TYPE
          WHERE LOCATION_TYPE_CODE NOT IN (1,2,4)
          ORDER BY LOCATION_TYPE_CODE;

END;
/
