CREATE OR REPLACE PROCEDURE COEUS.VU_UPD_PROPOSAL_APPROVED_SUBS (
    AV_PROPOSAL_NUMBER  IN  OSP$PROPOSAL_APPROVED_SUB.PROPOSAL_NUMBER%TYPE := NULL,
    AV_SEQUENCE_NUMBER  IN  OSP$PROPOSAL_APPROVED_SUB.SEQUENCE_NUMBER%TYPE := NULL,
    AV_SUBCONTRACTOR_NAME  IN  OSP$PROPOSAL_APPROVED_SUB.SUBCONTRACTOR_NAME%TYPE := NULL,
    AV_LOCATION_TYPE_CODE  IN  OSP$PROPOSAL_APPROVED_SUB.LOCATION_TYPE_CODE%TYPE := NULL,
    AV_ORGANIZATION_ID  IN  OSP$PROPOSAL_APPROVED_SUB.ORGANIZATION_ID%TYPE := NULL,
    AV_AMOUNT  IN  OSP$PROPOSAL_APPROVED_SUB.AMOUNT%TYPE := NULL,
    AV_UPDATE_TIMESTAMP  IN  OSP$PROPOSAL_APPROVED_SUB.UPDATE_TIMESTAMP%TYPE := NULL,
    AV_UPDATE_USER  IN  OSP$PROPOSAL_APPROVED_SUB.UPDATE_USER%TYPE := NULL,
    AW_PROPOSAL_NUMBER  IN  OSP$PROPOSAL_APPROVED_SUB.PROPOSAL_NUMBER%TYPE := NULL,
    AW_SEQUENCE_NUMBER  IN  OSP$PROPOSAL_APPROVED_SUB.SEQUENCE_NUMBER%TYPE := NULL,
    AW_LOCATION_TYPE_CODE  IN  OSP$PROPOSAL_APPROVED_SUB.LOCATION_TYPE_CODE%TYPE := NULL,
    AW_ORGANIZATION_ID  IN  OSP$PROPOSAL_APPROVED_SUB.ORGANIZATION_ID%TYPE := NULL,
    AC_TYPE  IN  VARCHAR2 )

IS

BEGIN

    IF AC_TYPE = 'I' THEN
        INSERT INTO OSP$PROPOSAL_APPROVED_SUB (
            PROPOSAL_NUMBER,
            SEQUENCE_NUMBER,
            SUBCONTRACTOR_NAME,
            LOCATION_TYPE_CODE,
            ORGANIZATION_ID,
            AMOUNT,
            UPDATE_TIMESTAMP,
            UPDATE_USER)
        VALUES (
            AV_PROPOSAL_NUMBER,
            AV_SEQUENCE_NUMBER,
            AV_SUBCONTRACTOR_NAME,
            AV_LOCATION_TYPE_CODE,
            AV_ORGANIZATION_ID,
            AV_AMOUNT,
            AV_UPDATE_TIMESTAMP,
            AV_UPDATE_USER);

    ELSIF AC_TYPE = 'U' THEN

        UPDATE OSP$PROPOSAL_APPROVED_SUB 
        SET PROPOSAL_NUMBER = AV_PROPOSAL_NUMBER,
            SEQUENCE_NUMBER = AV_SEQUENCE_NUMBER,
            SUBCONTRACTOR_NAME = AV_SUBCONTRACTOR_NAME,
            LOCATION_TYPE_CODE = AV_LOCATION_TYPE_CODE,
            ORGANIZATION_ID = AV_ORGANIZATION_ID,
            AMOUNT = AV_AMOUNT,
            UPDATE_TIMESTAMP = AV_UPDATE_TIMESTAMP,
            UPDATE_USER = AV_UPDATE_USER
        WHERE PROPOSAL_NUMBER = AW_PROPOSAL_NUMBER
        AND SEQUENCE_NUMBER = AW_SEQUENCE_NUMBER
        AND LOCATION_TYPE_CODE = AW_LOCATION_TYPE_CODE
        AND ORGANIZATION_ID = AW_ORGANIZATION_ID;

    ELSIF AC_TYPE = 'D' THEN

        DELETE FROM OSP$PROPOSAL_APPROVED_SUB
        WHERE PROPOSAL_NUMBER = AW_PROPOSAL_NUMBER
        AND SEQUENCE_NUMBER = AW_SEQUENCE_NUMBER
        AND LOCATION_TYPE_CODE = AW_LOCATION_TYPE_CODE
        AND ORGANIZATION_ID = AW_ORGANIZATION_ID;

    END IF;

   COMMIT;

END VU_UPD_PROPOSAL_APPROVED_SUBS;
/
