//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.3-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.19 at 04:23:48 EDT 
//


package gov.grants.apply.forms.gg_lobbyingform_v1_1.impl;

public class LobbyingFormTypeImpl implements gov.grants.apply.forms.gg_lobbyingform_v1_1.LobbyingFormType, com.sun.xml.bind.JAXBObject, gov.grants.apply.forms.attachments_v1.impl.runtime.UnmarshallableObject, gov.grants.apply.forms.attachments_v1.impl.runtime.XMLSerializable, gov.grants.apply.forms.attachments_v1.impl.runtime.ValidatableObject
{

    protected java.lang.String _AuthorizedRepresentativeTitle;
    protected java.lang.String _ApplicantName;
    protected java.lang.String _AuthorizedRepresentativeSignature;
    protected java.lang.String _FormVersion;
    protected java.util.Calendar _SubmittedDate;
    protected gov.grants.apply.system.globallibrary_v2.HumanNameDataType _AuthorizedRepresentativeName;
    public final static java.lang.Class version = (gov.grants.apply.forms.gg_lobbyingform_v1_1.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (gov.grants.apply.forms.gg_lobbyingform_v1_1.LobbyingFormType.class);
    }

    public java.lang.String getAuthorizedRepresentativeTitle() {
        return _AuthorizedRepresentativeTitle;
    }

    public void setAuthorizedRepresentativeTitle(java.lang.String value) {
        _AuthorizedRepresentativeTitle = value;
    }

    public java.lang.String getApplicantName() {
        return _ApplicantName;
    }

    public void setApplicantName(java.lang.String value) {
        _ApplicantName = value;
    }

    public java.lang.String getAuthorizedRepresentativeSignature() {
        return _AuthorizedRepresentativeSignature;
    }

    public void setAuthorizedRepresentativeSignature(java.lang.String value) {
        _AuthorizedRepresentativeSignature = value;
    }

    public java.lang.String getFormVersion() {
        return _FormVersion;
    }

    public void setFormVersion(java.lang.String value) {
        _FormVersion = value;
    }

    public java.util.Calendar getSubmittedDate() {
        return _SubmittedDate;
    }

    public void setSubmittedDate(java.util.Calendar value) {
        _SubmittedDate = value;
    }

    public gov.grants.apply.system.globallibrary_v2.HumanNameDataType getAuthorizedRepresentativeName() {
        return _AuthorizedRepresentativeName;
    }

    public void setAuthorizedRepresentativeName(gov.grants.apply.system.globallibrary_v2.HumanNameDataType value) {
        _AuthorizedRepresentativeName = value;
    }

    public gov.grants.apply.forms.attachments_v1.impl.runtime.UnmarshallingEventHandler createUnmarshaller(gov.grants.apply.forms.attachments_v1.impl.runtime.UnmarshallingContext context) {
        return new gov.grants.apply.forms.gg_lobbyingform_v1_1.impl.LobbyingFormTypeImpl.Unmarshaller(context);
    }

    public void serializeBody(gov.grants.apply.forms.attachments_v1.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        context.startElement("http://apply.grants.gov/forms/GG_LobbyingForm-V1-1", "ApplicantName");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _ApplicantName), "ApplicantName");
        } catch (java.lang.Exception e) {
            gov.grants.apply.forms.attachments_v1.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("http://apply.grants.gov/forms/GG_LobbyingForm-V1-1", "AuthorizedRepresentativeName");
        context.childAsURIs(((com.sun.xml.bind.JAXBObject) _AuthorizedRepresentativeName), "AuthorizedRepresentativeName");
        context.endNamespaceDecls();
        context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _AuthorizedRepresentativeName), "AuthorizedRepresentativeName");
        context.endAttributes();
        context.childAsBody(((com.sun.xml.bind.JAXBObject) _AuthorizedRepresentativeName), "AuthorizedRepresentativeName");
        context.endElement();
        context.startElement("http://apply.grants.gov/forms/GG_LobbyingForm-V1-1", "AuthorizedRepresentativeTitle");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _AuthorizedRepresentativeTitle), "AuthorizedRepresentativeTitle");
        } catch (java.lang.Exception e) {
            gov.grants.apply.forms.attachments_v1.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("http://apply.grants.gov/forms/GG_LobbyingForm-V1-1", "AuthorizedRepresentativeSignature");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _AuthorizedRepresentativeSignature), "AuthorizedRepresentativeSignature");
        } catch (java.lang.Exception e) {
            gov.grants.apply.forms.attachments_v1.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("http://apply.grants.gov/forms/GG_LobbyingForm-V1-1", "SubmittedDate");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(javax.xml.bind.DatatypeConverter.printDate(((java.util.Calendar) _SubmittedDate)), "SubmittedDate");
        } catch (java.lang.Exception e) {
            gov.grants.apply.forms.attachments_v1.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
    }

    public void serializeAttributes(gov.grants.apply.forms.attachments_v1.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        context.startAttribute("http://apply.grants.gov/forms/GG_LobbyingForm-V1-1", "FormVersion");
        try {
            context.text(((java.lang.String) _FormVersion), "FormVersion");
        } catch (java.lang.Exception e) {
            gov.grants.apply.forms.attachments_v1.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endAttribute();
    }

    public void serializeURIs(gov.grants.apply.forms.attachments_v1.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        context.getNamespaceContext().declareNamespace("http://apply.grants.gov/forms/GG_LobbyingForm-V1-1", null, true);
    }

    public java.lang.Class getPrimaryInterface() {
        return (gov.grants.apply.forms.gg_lobbyingform_v1_1.LobbyingFormType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000b"
+"expandedExpq\u0000~\u0000\u0002xpppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsr\u0000\'com."
+"sun.msv.grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000"
+"\u001fLcom/sun/msv/grammar/NameClass;xr\u0000\u001ecom.sun.msv.grammar.Elem"
+"entExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000\fcontentMode"
+"lq\u0000~\u0000\u0002xq\u0000~\u0000\u0003pp\u0000sq\u0000~\u0000\u0000ppsr\u0000\u001bcom.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000"
+"\u0004namet\u0000\u001dLcom/sun/msv/util/StringPair;xq\u0000~\u0000\u0003ppsr\u0000\'com.sun.msv"
+".datatype.xsd.MaxLengthFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001I\u0000\tmaxLengthxr\u00009com.s"
+"un.msv.datatype.xsd.DataTypeWithValueConstraintFacet\"\u00a7Ro\u00ca\u00c7\u008aT"
+"\u0002\u0000\u0000xr\u0000*com.sun.msv.datatype.xsd.DataTypeWithFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0005"
+"Z\u0000\fisFacetFixedZ\u0000\u0012needValueCheckFlagL\u0000\bbaseTypet\u0000)Lcom/sun/m"
+"sv/datatype/xsd/XSDatatypeImpl;L\u0000\fconcreteTypet\u0000\'Lcom/sun/ms"
+"v/datatype/xsd/ConcreteType;L\u0000\tfacetNamet\u0000\u0012Ljava/lang/String"
+";xr\u0000\'com.sun.msv.datatype.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fna"
+"mespaceUriq\u0000~\u0000\u0018L\u0000\btypeNameq\u0000~\u0000\u0018L\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/"
+"datatype/xsd/WhiteSpaceProcessor;xpt\u00001http://apply.grants.go"
+"v/system/GlobalLibrary-V2.0t\u0000\u0018OrganizationNameDataTypesr\u00005co"
+"m.sun.msv.datatype.xsd.WhiteSpaceProcessor$Preserve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002"
+"\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000"
+"\u0000xp\u0000\u0001sr\u0000\'com.sun.msv.datatype.xsd.MinLengthFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001I"
+"\u0000\tminLengthxq\u0000~\u0000\u0014q\u0000~\u0000\u001cq\u0000~\u0000\u001dq\u0000~\u0000 \u0000\u0000sr\u0000#com.sun.msv.datatype.x"
+"sd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxr\u0000*com.sun.msv.data"
+"type.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatyp"
+"e.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0019t\u0000 http://www.w3.org/2001"
+"/XMLSchemat\u0000\u0006stringq\u0000~\u0000 \u0001q\u0000~\u0000&t\u0000\tminLength\u0000\u0000\u0000\u0001q\u0000~\u0000&t\u0000\tmaxLen"
+"gth\u0000\u0000\u0000<sr\u00000com.sun.msv.grammar.Expression$NullSetExpression\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003ppsr\u0000\u001bcom.sun.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002"
+"L\u0000\tlocalNameq\u0000~\u0000\u0018L\u0000\fnamespaceURIq\u0000~\u0000\u0018xpq\u0000~\u0000\u001dq\u0000~\u0000\u001csr\u0000\u001dcom.sun"
+".msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001ppsr\u0000 com.sun.msv.gra"
+"mmar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameClassq\u0000~\u0000\u000bxq\u0000~"
+"\u0000\u0003sr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psq\u0000~\u0000\u000fppsr\u0000\"co"
+"m.sun.msv.datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000$q\u0000~\u0000\'t\u0000\u0005QNa"
+"mesr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Collapse\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u001fq\u0000~\u0000,sq\u0000~\u0000-q\u0000~\u00008q\u0000~\u0000\'sr\u0000#com.sun.msv.grammar"
+".SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u0018L\u0000\fnamespaceURIq"
+"\u0000~\u0000\u0018xr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0004typet\u0000)"
+"http://www.w3.org/2001/XMLSchema-instancesr\u00000com.sun.msv.gra"
+"mmar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003sq\u0000~\u00003\u0001q\u0000~"
+"\u0000Bsq\u0000~\u0000<t\u0000\rApplicantNamet\u00002http://apply.grants.gov/forms/GG_"
+"LobbyingForm-V1-1sq\u0000~\u0000\npp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\npp\u0000sq\u0000~\u0000/ppsr\u0000 com.s"
+"un.msv.grammar.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.msv.gramma"
+"r.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0002xq\u0000~\u0000\u0003q\u0000~\u00004psq\u0000~\u00001q\u0000~\u00004psr\u00002"
+"com.sun.msv.grammar.Expression$AnyStringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000"
+"\u0000xq\u0000~\u0000\u0003q\u0000~\u0000Cq\u0000~\u0000Psr\u0000 com.sun.msv.grammar.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0001\u0002\u0000\u0000xq\u0000~\u0000=q\u0000~\u0000Bsq\u0000~\u0000<t\u0000:gov.grants.apply.system.globallibrar"
+"y_v2.HumanNameDataTypet\u0000+http://java.sun.com/jaxb/xjc/dummy-"
+"elementssq\u0000~\u0000/ppsq\u0000~\u00001q\u0000~\u00004pq\u0000~\u00005q\u0000~\u0000>q\u0000~\u0000Bsq\u0000~\u0000<t\u0000\u001cAuthoriz"
+"edRepresentativeNameq\u0000~\u0000Fsq\u0000~\u0000\npp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u000fppsq\u0000~\u0000\u0013q\u0000~\u0000"
+"\u001ct\u0000\u0012HumanTitleDataTypeq\u0000~\u0000 \u0000\u0001sq\u0000~\u0000!q\u0000~\u0000\u001cq\u0000~\u0000^q\u0000~\u0000 \u0000\u0000q\u0000~\u0000&q\u0000~"
+"\u0000&q\u0000~\u0000)\u0000\u0000\u0000\u0001q\u0000~\u0000&q\u0000~\u0000*\u0000\u0000\u0000-q\u0000~\u0000,sq\u0000~\u0000-q\u0000~\u0000^q\u0000~\u0000\u001csq\u0000~\u0000/ppsq\u0000~\u00001"
+"q\u0000~\u00004pq\u0000~\u00005q\u0000~\u0000>q\u0000~\u0000Bsq\u0000~\u0000<t\u0000\u001dAuthorizedRepresentativeTitleq"
+"\u0000~\u0000Fsq\u0000~\u0000\npp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u000fppsq\u0000~\u0000\u0013q\u0000~\u0000\u001ct\u0000\u0011SignatureDataType"
+"q\u0000~\u0000 \u0000\u0001sq\u0000~\u0000!q\u0000~\u0000\u001cq\u0000~\u0000iq\u0000~\u0000 \u0000\u0000q\u0000~\u0000&q\u0000~\u0000&q\u0000~\u0000)\u0000\u0000\u0000\u0001q\u0000~\u0000&q\u0000~\u0000*\u0000"
+"\u0000\u0000\u0090q\u0000~\u0000,sq\u0000~\u0000-q\u0000~\u0000iq\u0000~\u0000\u001csq\u0000~\u0000/ppsq\u0000~\u00001q\u0000~\u00004pq\u0000~\u00005q\u0000~\u0000>q\u0000~\u0000Bs"
+"q\u0000~\u0000<t\u0000!AuthorizedRepresentativeSignatureq\u0000~\u0000Fsq\u0000~\u0000\npp\u0000sq\u0000~\u0000"
+"\u0000ppsq\u0000~\u0000\u000fppsr\u0000!com.sun.msv.datatype.xsd.DateType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000x"
+"r\u0000)com.sun.msv.datatype.xsd.DateTimeBaseType\u0014W\u001a@3\u00a5\u00b4\u00e5\u0002\u0000\u0000xq\u0000~\u0000"
+"$q\u0000~\u0000\'t\u0000\u0004dateq\u0000~\u0000:q\u0000~\u0000,sq\u0000~\u0000-q\u0000~\u0000vq\u0000~\u0000\'sq\u0000~\u0000/ppsq\u0000~\u00001q\u0000~\u00004pq"
+"\u0000~\u00005q\u0000~\u0000>q\u0000~\u0000Bsq\u0000~\u0000<t\u0000\rSubmittedDateq\u0000~\u0000Fsq\u0000~\u00001ppsr\u0000\u001ccom.sun"
+".msv.grammar.ValueExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtq\u0000~\u0000\u0010L\u0000\u0004nameq\u0000~\u0000\u0011L\u0000\u0005val"
+"uet\u0000\u0012Ljava/lang/Object;xq\u0000~\u0000\u0003ppsq\u0000~\u0000\u0013q\u0000~\u0000\u001ct\u0000\u0013FormVersionData"
+"Typeq\u0000~\u0000 \u0000\u0001sq\u0000~\u0000!q\u0000~\u0000\u001cq\u0000~\u0000\u0081q\u0000~\u0000 \u0000\u0000q\u0000~\u0000&q\u0000~\u0000&q\u0000~\u0000)\u0000\u0000\u0000\u0001q\u0000~\u0000&q\u0000"
+"~\u0000*\u0000\u0000\u0000\u001esq\u0000~\u0000-q\u0000~\u0000\u0081q\u0000~\u0000\u001ct\u0000\u00031.1sq\u0000~\u0000<t\u0000\u000bFormVersionq\u0000~\u0000Fsr\u0000\"co"
+"m.sun.msv.grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lco"
+"m/sun/msv/grammar/ExpressionPool$ClosedHash;xpsr\u0000-com.sun.ms"
+"v.grammar.ExpressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstr"
+"eamVersionL\u0000\u0006parentt\u0000$Lcom/sun/msv/grammar/ExpressionPool;xp"
+"\u0000\u0000\u0000\u0011\u0001pq\u0000~\u0000[q\u0000~\u00000q\u0000~\u0000Vq\u0000~\u0000aq\u0000~\u0000lq\u0000~\u0000xq\u0000~\u0000fq\u0000~\u0000\u0005q\u0000~\u0000qq\u0000~\u0000\u0006q\u0000~\u0000"
+"Hq\u0000~\u0000Jq\u0000~\u0000\u000eq\u0000~\u0000\bq\u0000~\u0000Mq\u0000~\u0000\u0007q\u0000~\u0000\tx"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends gov.grants.apply.forms.attachments_v1.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(gov.grants.apply.forms.attachments_v1.impl.runtime.UnmarshallingContext context) {
            super(context, "-------------------");
        }

        protected Unmarshaller(gov.grants.apply.forms.attachments_v1.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return gov.grants.apply.forms.gg_lobbyingform_v1_1.impl.LobbyingFormTypeImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  6 :
                        if (("AuthorizedRepresentativeName" == ___local)&&("http://apply.grants.gov/forms/GG_LobbyingForm-V1-1" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 7;
                            return ;
                        }
                        break;
                    case  3 :
                        if (("ApplicantName" == ___local)&&("http://apply.grants.gov/forms/GG_LobbyingForm-V1-1" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 4;
                            return ;
                        }
                        break;
                    case  12 :
                        if (("AuthorizedRepresentativeSignature" == ___local)&&("http://apply.grants.gov/forms/GG_LobbyingForm-V1-1" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 13;
                            return ;
                        }
                        break;
                    case  9 :
                        if (("AuthorizedRepresentativeTitle" == ___local)&&("http://apply.grants.gov/forms/GG_LobbyingForm-V1-1" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 10;
                            return ;
                        }
                        break;
                    case  18 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  15 :
                        if (("SubmittedDate" == ___local)&&("http://apply.grants.gov/forms/GG_LobbyingForm-V1-1" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 16;
                            return ;
                        }
                        break;
                    case  0 :
                        attIdx = context.getAttribute("http://apply.grants.gov/forms/GG_LobbyingForm-V1-1", "FormVersion");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText1(v);
                            state = 3;
                            continue outer;
                        }
                        break;
                    case  7 :
                        if (("PrefixName" == ___local)&&("http://apply.grants.gov/system/GlobalLibrary-V2.0" == ___uri)) {
                            _AuthorizedRepresentativeName = ((gov.grants.apply.system.globallibrary_v2.impl.HumanNameDataTypeImpl) spawnChildFromEnterElement((gov.grants.apply.system.globallibrary_v2.impl.HumanNameDataTypeImpl.class), 8, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("FirstName" == ___local)&&("http://apply.grants.gov/system/GlobalLibrary-V2.0" == ___uri)) {
                            _AuthorizedRepresentativeName = ((gov.grants.apply.system.globallibrary_v2.impl.HumanNameDataTypeImpl) spawnChildFromEnterElement((gov.grants.apply.system.globallibrary_v2.impl.HumanNameDataTypeImpl.class), 8, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        private void eatText1(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _FormVersion = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  8 :
                        if (("AuthorizedRepresentativeName" == ___local)&&("http://apply.grants.gov/forms/GG_LobbyingForm-V1-1" == ___uri)) {
                            context.popAttributes();
                            state = 9;
                            return ;
                        }
                        break;
                    case  18 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  17 :
                        if (("SubmittedDate" == ___local)&&("http://apply.grants.gov/forms/GG_LobbyingForm-V1-1" == ___uri)) {
                            context.popAttributes();
                            state = 18;
                            return ;
                        }
                        break;
                    case  0 :
                        attIdx = context.getAttribute("http://apply.grants.gov/forms/GG_LobbyingForm-V1-1", "FormVersion");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText1(v);
                            state = 3;
                            continue outer;
                        }
                        break;
                    case  11 :
                        if (("AuthorizedRepresentativeTitle" == ___local)&&("http://apply.grants.gov/forms/GG_LobbyingForm-V1-1" == ___uri)) {
                            context.popAttributes();
                            state = 12;
                            return ;
                        }
                        break;
                    case  14 :
                        if (("AuthorizedRepresentativeSignature" == ___local)&&("http://apply.grants.gov/forms/GG_LobbyingForm-V1-1" == ___uri)) {
                            context.popAttributes();
                            state = 15;
                            return ;
                        }
                        break;
                    case  5 :
                        if (("ApplicantName" == ___local)&&("http://apply.grants.gov/forms/GG_LobbyingForm-V1-1" == ___uri)) {
                            context.popAttributes();
                            state = 6;
                            return ;
                        }
                        break;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  18 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  0 :
                        if (("FormVersion" == ___local)&&("http://apply.grants.gov/forms/GG_LobbyingForm-V1-1" == ___uri)) {
                            state = 1;
                            return ;
                        }
                        break;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  2 :
                        if (("FormVersion" == ___local)&&("http://apply.grants.gov/forms/GG_LobbyingForm-V1-1" == ___uri)) {
                            state = 3;
                            return ;
                        }
                        break;
                    case  18 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  0 :
                        attIdx = context.getAttribute("http://apply.grants.gov/forms/GG_LobbyingForm-V1-1", "FormVersion");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText1(v);
                            state = 3;
                            continue outer;
                        }
                        break;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  16 :
                            eatText2(value);
                            state = 17;
                            return ;
                        case  1 :
                            eatText1(value);
                            state = 2;
                            return ;
                        case  18 :
                            revertToParentFromText(value);
                            return ;
                        case  0 :
                            attIdx = context.getAttribute("http://apply.grants.gov/forms/GG_LobbyingForm-V1-1", "FormVersion");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                eatText1(v);
                                state = 3;
                                continue outer;
                            }
                            break;
                        case  4 :
                            eatText3(value);
                            state = 5;
                            return ;
                        case  10 :
                            eatText4(value);
                            state = 11;
                            return ;
                        case  13 :
                            eatText5(value);
                            state = 14;
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

        private void eatText2(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _SubmittedDate = javax.xml.bind.DatatypeConverter.parseDate(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText3(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _ApplicantName = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText4(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _AuthorizedRepresentativeTitle = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText5(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _AuthorizedRepresentativeSignature = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

    }

}
