//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.02.13 at 11:23:34 AM EST 
//


package gov.grants.apply.forms.rr_fednonfedbudget_v1;


/**
 * Java content class for SummaryDataType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at http://apply.grants.gov/forms/schemas/RR_FedNonFedBudget-V1.0.xsd line 116)
 * <p>
 * <pre>
 * &lt;complexType name="SummaryDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FederalSummary" type="{http://apply.grants.gov/system/GlobalLibrary-V1.0}BudgetTotalAmountDataType"/>
 *         &lt;element name="NonFederalSummary" type="{http://apply.grants.gov/system/GlobalLibrary-V1.0}BudgetTotalAmountDataType"/>
 *         &lt;element name="TotalFedNonFedSummary" type="{http://apply.grants.gov/system/GlobalLibrary-V1.0}BudgetTotalAmountDataType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface SummaryDataType {


    /**
     * Gets the value of the totalFedNonFedSummary property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigDecimal}
     */
    java.math.BigDecimal getTotalFedNonFedSummary();

    /**
     * Sets the value of the totalFedNonFedSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigDecimal}
     */
    void setTotalFedNonFedSummary(java.math.BigDecimal value);

    /**
     * Gets the value of the nonFederalSummary property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigDecimal}
     */
    java.math.BigDecimal getNonFederalSummary();

    /**
     * Sets the value of the nonFederalSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigDecimal}
     */
    void setNonFederalSummary(java.math.BigDecimal value);

    /**
     * Gets the value of the federalSummary property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigDecimal}
     */
    java.math.BigDecimal getFederalSummary();

    /**
     * Sets the value of the federalSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigDecimal}
     */
    void setFederalSummary(java.math.BigDecimal value);

}
