//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.26 at 08:55:40 CDT 
//


package gov.grants.apply.forms.phs_assignmentrequestform_2_0_v2.verification;

public class PHSAssignmentRequestForm20Verifier
    extends gov.grants.apply.forms.phs_assignmentrequestform_2_0_v2.verification.PHSAssignmentRequestForm20TypeVerifier
{


    public void check(de.fzi.dbs.verification.event.AbstractVerificationEventLocator parentLocator, javax.xml.bind.ValidationEventHandler handler, gov.grants.apply.forms.phs_assignmentrequestform_2_0_v2.PHSAssignmentRequestForm20 master) {
        super.check(parentLocator, handler, master);
    }

    public void check(de.fzi.dbs.verification.event.AbstractVerificationEventLocator parentLocator, javax.xml.bind.ValidationEventHandler handler, java.lang.Object object) {
        check(parentLocator, handler, ((gov.grants.apply.forms.phs_assignmentrequestform_2_0_v2.PHSAssignmentRequestForm20) object));
    }

    public void check(javax.xml.bind.ValidationEventHandler handler, java.lang.Object object) {
        check(null, handler, ((gov.grants.apply.forms.phs_assignmentrequestform_2_0_v2.PHSAssignmentRequestForm20) object));
    }

}
