/*
 * IDCRates.java
 *
 * Created on March 25, 2004, 7:39 PM
 */

package edu.mit.coeus.instprop.gui;

import javax.swing.*;

import edu.mit.coeus.gui.*;
import edu.mit.coeus.utils.LimitedPlainDocument;


/**
 *
 * @author  ajaygm
 */
public class IDCRatesForm extends javax.swing.JComponent {
    
    /** Creates new form IDCRates */
    public IDCRatesForm() {
        initComponents();
        txtArComments.setDocument(new LimitedPlainDocument(3878));
    }
    
    public static void main(String s[]){
        JFrame frame = new JFrame("Proposal IP Review");
        IDCRatesForm iDCRatesForm = new IDCRatesForm();
        frame.getContentPane().add(iDCRatesForm);
        frame.setSize(900, 675);
        frame.show();
     }
    
    public javax.swing.JTable getTableInstance(){
      return tblIDCRates;
  }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        lblIDCRates = new javax.swing.JLabel();
        scrPnIDCRates = new javax.swing.JScrollPane();
        tblIDCRates = new javax.swing.JTable(){
            public void changeSelection(int row, int column, boolean toggle, boolean extend){
                super.changeSelection(row, column, toggle, extend);
                if(getTableInstance().isCellEditable(row,column)){
                    getTableInstance().editCellAt(row,column);
                    getTableInstance().getEditorComponent().requestFocus();
                }
            }
        };
        lblComments = new javax.swing.JLabel();
        srcPnComments = new javax.swing.JScrollPane();
        txtArComments = new javax.swing.JTextArea();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        pnlAdd = new javax.swing.JPanel();
        tblAdd = new javax.swing.JTable();

        setLayout(new java.awt.GridBagLayout());

        lblIDCRates.setFont(CoeusFontFactory.getLabelFont());
        lblIDCRates.setText("IDC Rates");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        add(lblIDCRates, gridBagConstraints);

        scrPnIDCRates.setBorder(new javax.swing.border.EtchedBorder());
        scrPnIDCRates.setMinimumSize(new java.awt.Dimension(800, 200));
        scrPnIDCRates.setPreferredSize(new java.awt.Dimension(800, 400));
        tblIDCRates.setFont(CoeusFontFactory.getNormalFont());
        tblIDCRates.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblIDCRates.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblIDCRatesMouseClicked(evt);
            }
        });

        scrPnIDCRates.setViewportView(tblIDCRates);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(scrPnIDCRates, gridBagConstraints);

        lblComments.setFont(CoeusFontFactory.getLabelFont());
        lblComments.setText("Comments");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(lblComments, gridBagConstraints);

        srcPnComments.setMinimumSize(new java.awt.Dimension(550, 60));
        srcPnComments.setPreferredSize(new java.awt.Dimension(550, 60));
        txtArComments.setFont(CoeusFontFactory.getNormalFont()
        );
        txtArComments.setLineWrap(true);
        txtArComments.setWrapStyleWord(true);
        srcPnComments.setViewportView(txtArComments);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 4, 0);
        add(srcPnComments, gridBagConstraints);

        btnAdd.setFont(CoeusFontFactory.getLabelFont());
        btnAdd.setMnemonic('A');
        btnAdd.setText("Add");
        btnAdd.setMinimumSize(new java.awt.Dimension(80, 25));
        btnAdd.setPreferredSize(new java.awt.Dimension(80, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 3);
        add(btnAdd, gridBagConstraints);

        btnDelete.setFont(CoeusFontFactory.getLabelFont());
        btnDelete.setMnemonic('D');
        btnDelete.setText("Delete");
        btnDelete.setMinimumSize(new java.awt.Dimension(80, 25));
        btnDelete.setPreferredSize(new java.awt.Dimension(80, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 3);
        add(btnDelete, gridBagConstraints);

        pnlAdd.setLayout(new java.awt.GridBagLayout());

        pnlAdd.setPreferredSize(new java.awt.Dimension(150, 25));
        tblAdd.setFont(CoeusFontFactory.getNormalFont());
        tblAdd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlAdd.add(tblAdd, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(pnlAdd, gridBagConstraints);

    }//GEN-END:initComponents

    private void tblIDCRatesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblIDCRatesMouseClicked
        // Add your handling code here:
        javax.swing.SwingUtilities.invokeLater( new Runnable() {
            public void run() {
                tblIDCRates.dispatchEvent(new java.awt.event.KeyEvent(
                tblIDCRates,java.awt.event.KeyEvent.KEY_PRESSED,0,0,java.awt.event.KeyEvent.VK_F2,
                java.awt.event.KeyEvent.CHAR_UNDEFINED) );
            }
        });
    }//GEN-LAST:event_tblIDCRatesMouseClicked
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAdd;
    public javax.swing.JButton btnDelete;
    public javax.swing.JLabel lblComments;
    public javax.swing.JLabel lblIDCRates;
    public javax.swing.JPanel pnlAdd;
    public javax.swing.JScrollPane scrPnIDCRates;
    public javax.swing.JScrollPane srcPnComments;
    public javax.swing.JTable tblAdd;
    public javax.swing.JTable tblIDCRates;
    public javax.swing.JTextArea txtArComments;
    // End of variables declaration//GEN-END:variables
    
}
