//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.11.17 at 10:40:49 EST 
//


package edu.mit.coeus.utils.xml.bean.reportingReq;


/**
 * Java content class for awardReportingRequirement element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/temp/awardReportingRequirements.xsd line 4)
 * <p>
 * <pre>
 * &lt;element name="awardReportingRequirement">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="reportingReqs" type="{}reportingRequirement" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="currentDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 */
public interface AwardReportingRequirement
    extends javax.xml.bind.Element, edu.mit.coeus.utils.xml.bean.reportingReq.AwardReportingRequirementType
{


}
