//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.3-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.19 at 04:23:48 EDT 
//


package gov.grants.apply.forms.nasa_senkpsupdtsht_v1;


/**
 * Java content class for Senior_Key_PersonType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/s2s/build/cust/NASA_SeniorKeyPersonSupplementalDataSheet-V1.0.xsd line 94)
 * <p>
 * <pre>
 * &lt;complexType name="Senior_Key_PersonType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SeniorKeyPersonName" type="{http://apply.grants.gov/system/GlobalLibrary-V2.0}HumanNameDataType"/>
 *         &lt;element name="NASACo-Itype" type="{http://apply.grants.gov/forms/NASA_SenKPSupDtSht-V1.0}Co-ItypeDataType" minOccurs="0"/>
 *         &lt;element name="USGovernmentParticipation" type="{http://apply.grants.gov/system/GlobalLibrary-V2.0}YesNoDataType"/>
 *         &lt;element name="FederalAgency" type="{http://apply.grants.gov/forms/NASA_SenKPSupDtSht-V1.0}FederalAgencyDataType" minOccurs="0"/>
 *         &lt;element name="FederalAgencyDollar" type="{http://apply.grants.gov/system/GlobalLibrary-V2.0}BudgetAmountDataType" minOccurs="0"/>
 *         &lt;element name="InternationalParticipation" type="{http://apply.grants.gov/system/GlobalLibrary-V2.0}YesNoDataType"/>
 *         &lt;element name="StatementofCommitment" type="{http://apply.grants.gov/system/Attachments-V1.0}AttachmentGroupMin0Max100DataType" minOccurs="0"/>
 *         &lt;element name="BudgetDetails" type="{http://apply.grants.gov/system/Attachments-V1.0}AttachmentGroupMin0Max100DataType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface SeniorKeyPersonType {


    /**
     * Gets the value of the seniorKeyPersonName property.
     * 
     * @return
     *     possible object is
     *     {@link gov.grants.apply.system.globallibrary_v2.HumanNameDataType}
     */
    gov.grants.apply.system.globallibrary_v2.HumanNameDataType getSeniorKeyPersonName();

    /**
     * Sets the value of the seniorKeyPersonName property.
     * 
     * @param value
     *     allowed object is
     *     {@link gov.grants.apply.system.globallibrary_v2.HumanNameDataType}
     */
    void setSeniorKeyPersonName(gov.grants.apply.system.globallibrary_v2.HumanNameDataType value);

    /**
     * Gets the value of the internationalParticipation property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getInternationalParticipation();

    /**
     * Sets the value of the internationalParticipation property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setInternationalParticipation(java.lang.String value);

    /**
     * Gets the value of the federalAgencyDollar property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigDecimal}
     */
    java.math.BigDecimal getFederalAgencyDollar();

    /**
     * Sets the value of the federalAgencyDollar property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigDecimal}
     */
    void setFederalAgencyDollar(java.math.BigDecimal value);

    /**
     * Gets the value of the budgetDetails property.
     * 
     * @return
     *     possible object is
     *     {@link gov.grants.apply.system.attachments_v1.AttachmentGroupMin0Max100DataType}
     */
    gov.grants.apply.system.attachments_v1.AttachmentGroupMin0Max100DataType getBudgetDetails();

    /**
     * Sets the value of the budgetDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link gov.grants.apply.system.attachments_v1.AttachmentGroupMin0Max100DataType}
     */
    void setBudgetDetails(gov.grants.apply.system.attachments_v1.AttachmentGroupMin0Max100DataType value);

    /**
     * Gets the value of the statementofCommitment property.
     * 
     * @return
     *     possible object is
     *     {@link gov.grants.apply.system.attachments_v1.AttachmentGroupMin0Max100DataType}
     */
    gov.grants.apply.system.attachments_v1.AttachmentGroupMin0Max100DataType getStatementofCommitment();

    /**
     * Sets the value of the statementofCommitment property.
     * 
     * @param value
     *     allowed object is
     *     {@link gov.grants.apply.system.attachments_v1.AttachmentGroupMin0Max100DataType}
     */
    void setStatementofCommitment(gov.grants.apply.system.attachments_v1.AttachmentGroupMin0Max100DataType value);

    /**
     * Gets the value of the federalAgency property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getFederalAgency();

    /**
     * Sets the value of the federalAgency property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setFederalAgency(java.lang.String value);

    /**
     * Gets the value of the nasaCoItype property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getNASACoItype();

    /**
     * Sets the value of the nasaCoItype property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setNASACoItype(java.lang.String value);

    /**
     * Gets the value of the usGovernmentParticipation property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getUSGovernmentParticipation();

    /**
     * Sets the value of the usGovernmentParticipation property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setUSGovernmentParticipation(java.lang.String value);

}
