//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.30 at 02:55:50 CDT 
//


package gov.grants.apply.forms.phs_fellowship_supplemental_v3_1.verification;

public class PHSFellowshipSupplemental31Verifier
    extends gov.grants.apply.forms.phs_fellowship_supplemental_v3_1.verification.PHSFellowshipSupplemental31TypeVerifier
{


    public void check(de.fzi.dbs.verification.event.AbstractVerificationEventLocator parentLocator, javax.xml.bind.ValidationEventHandler handler, gov.grants.apply.forms.phs_fellowship_supplemental_v3_1.PHSFellowshipSupplemental31 master) {
        super.check(parentLocator, handler, master);
    }

    public void check(de.fzi.dbs.verification.event.AbstractVerificationEventLocator parentLocator, javax.xml.bind.ValidationEventHandler handler, java.lang.Object object) {
        check(parentLocator, handler, ((gov.grants.apply.forms.phs_fellowship_supplemental_v3_1.PHSFellowshipSupplemental31) object));
    }

    public void check(javax.xml.bind.ValidationEventHandler handler, java.lang.Object object) {
        check(null, handler, ((gov.grants.apply.forms.phs_fellowship_supplemental_v3_1.PHSFellowshipSupplemental31) object));
    }

}
