//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.17 at 08:39:35 PM GMT+05:30 
//


package edu.mit.coeus.utils.xml.bean.protocol.impl;

public class ProtoCorrespTypeImpl implements edu.mit.coeus.utils.xml.bean.protocol.ProtoCorrespType, com.sun.xml.bind.JAXBObject, edu.mit.coeus.utils.xml.bean.protocol.impl.runtime.UnmarshallableObject, edu.mit.coeus.utils.xml.bean.protocol.impl.runtime.XMLSerializable, edu.mit.coeus.utils.xml.bean.protocol.impl.runtime.ValidatableObject
{

    protected com.sun.xml.bind.util.ListImpl _ProtoCorrespDefRecip;
    protected java.lang.String _Description;
    protected com.sun.xml.bind.util.ListImpl _ProtoCorrespRecipients;
    protected com.sun.xml.bind.util.ListImpl _ProtoCorrespTempl;
    protected java.util.Calendar _UpdateTimestamp;
    protected boolean has_ProtoCorrespTypeCode;
    protected int _ProtoCorrespTypeCode;
    protected com.sun.xml.bind.util.ListImpl _ProtocolCorrespondence;
    protected java.lang.String _ModuleId;
    protected java.lang.String _UpdateUser;
    public final static java.lang.Class version = (edu.mit.coeus.utils.xml.bean.protocol.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (edu.mit.coeus.utils.xml.bean.protocol.ProtoCorrespType.class);
    }

    protected com.sun.xml.bind.util.ListImpl _getProtoCorrespDefRecip() {
        if (_ProtoCorrespDefRecip == null) {
            _ProtoCorrespDefRecip = new com.sun.xml.bind.util.ListImpl(new java.util.ArrayList());
        }
        return _ProtoCorrespDefRecip;
    }

    public java.util.List getProtoCorrespDefRecip() {
        return _getProtoCorrespDefRecip();
    }

    public java.lang.String getDescription() {
        return _Description;
    }

    public void setDescription(java.lang.String value) {
        _Description = value;
    }

    protected com.sun.xml.bind.util.ListImpl _getProtoCorrespRecipients() {
        if (_ProtoCorrespRecipients == null) {
            _ProtoCorrespRecipients = new com.sun.xml.bind.util.ListImpl(new java.util.ArrayList());
        }
        return _ProtoCorrespRecipients;
    }

    public java.util.List getProtoCorrespRecipients() {
        return _getProtoCorrespRecipients();
    }

    protected com.sun.xml.bind.util.ListImpl _getProtoCorrespTempl() {
        if (_ProtoCorrespTempl == null) {
            _ProtoCorrespTempl = new com.sun.xml.bind.util.ListImpl(new java.util.ArrayList());
        }
        return _ProtoCorrespTempl;
    }

    public java.util.List getProtoCorrespTempl() {
        return _getProtoCorrespTempl();
    }

    public java.util.Calendar getUpdateTimestamp() {
        return _UpdateTimestamp;
    }

    public void setUpdateTimestamp(java.util.Calendar value) {
        _UpdateTimestamp = value;
    }

    public int getProtoCorrespTypeCode() {
        return _ProtoCorrespTypeCode;
    }

    public void setProtoCorrespTypeCode(int value) {
        _ProtoCorrespTypeCode = value;
        has_ProtoCorrespTypeCode = true;
    }

    protected com.sun.xml.bind.util.ListImpl _getProtocolCorrespondence() {
        if (_ProtocolCorrespondence == null) {
            _ProtocolCorrespondence = new com.sun.xml.bind.util.ListImpl(new java.util.ArrayList());
        }
        return _ProtocolCorrespondence;
    }

    public java.util.List getProtocolCorrespondence() {
        return _getProtocolCorrespondence();
    }

    public java.lang.String getModuleId() {
        return _ModuleId;
    }

    public void setModuleId(java.lang.String value) {
        _ModuleId = value;
    }

    public java.lang.String getUpdateUser() {
        return _UpdateUser;
    }

    public void setUpdateUser(java.lang.String value) {
        _UpdateUser = value;
    }

    public edu.mit.coeus.utils.xml.bean.protocol.impl.runtime.UnmarshallingEventHandler createUnmarshaller(edu.mit.coeus.utils.xml.bean.protocol.impl.runtime.UnmarshallingContext context) {
        return new edu.mit.coeus.utils.xml.bean.protocol.impl.ProtoCorrespTypeImpl.Unmarshaller(context);
    }

    public void serializeBody(edu.mit.coeus.utils.xml.bean.protocol.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx1 = 0;
        final int len1 = ((_ProtoCorrespDefRecip == null)? 0 :_ProtoCorrespDefRecip.size());
        int idx3 = 0;
        final int len3 = ((_ProtoCorrespRecipients == null)? 0 :_ProtoCorrespRecipients.size());
        int idx4 = 0;
        final int len4 = ((_ProtoCorrespTempl == null)? 0 :_ProtoCorrespTempl.size());
        if (!has_ProtoCorrespTypeCode) {
            context.reportError(com.sun.xml.bind.serializer.Util.createMissingObjectError(this, "ProtoCorrespTypeCode"));
        }
        int idx7 = 0;
        final int len7 = ((_ProtocolCorrespondence == null)? 0 :_ProtocolCorrespondence.size());
        context.startElement("http://www.w3.org/2001/ProtocolSummarySchema", "ProtoCorrespTypeCode");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(javax.xml.bind.DatatypeConverter.printInt(((int) _ProtoCorrespTypeCode)), "ProtoCorrespTypeCode");
        } catch (java.lang.Exception e) {
            edu.mit.coeus.utils.xml.bean.protocol.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("http://www.w3.org/2001/ProtocolSummarySchema", "Description");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _Description), "Description");
        } catch (java.lang.Exception e) {
            edu.mit.coeus.utils.xml.bean.protocol.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("http://www.w3.org/2001/ProtocolSummarySchema", "UpdateTimestamp");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(com.sun.msv.datatype.xsd.DateTimeType.theInstance.serializeJavaObject(((java.util.Calendar) _UpdateTimestamp), null), "UpdateTimestamp");
        } catch (java.lang.Exception e) {
            edu.mit.coeus.utils.xml.bean.protocol.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("http://www.w3.org/2001/ProtocolSummarySchema", "UpdateUser");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _UpdateUser), "UpdateUser");
        } catch (java.lang.Exception e) {
            edu.mit.coeus.utils.xml.bean.protocol.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("http://www.w3.org/2001/ProtocolSummarySchema", "ModuleId");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _ModuleId), "ModuleId");
        } catch (java.lang.Exception e) {
            edu.mit.coeus.utils.xml.bean.protocol.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        while (idx7 != len7) {
            context.startElement("http://www.w3.org/2001/ProtocolSummarySchema", "ProtocolCorrespondence");
            int idx_10 = idx7;
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _ProtocolCorrespondence.get(idx_10 ++)), "ProtocolCorrespondence");
            context.endNamespaceDecls();
            int idx_11 = idx7;
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _ProtocolCorrespondence.get(idx_11 ++)), "ProtocolCorrespondence");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _ProtocolCorrespondence.get(idx7 ++)), "ProtocolCorrespondence");
            context.endElement();
        }
        while (idx1 != len1) {
            context.startElement("http://www.w3.org/2001/ProtocolSummarySchema", "ProtoCorrespDefRecip");
            int idx_12 = idx1;
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _ProtoCorrespDefRecip.get(idx_12 ++)), "ProtoCorrespDefRecip");
            context.endNamespaceDecls();
            int idx_13 = idx1;
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _ProtoCorrespDefRecip.get(idx_13 ++)), "ProtoCorrespDefRecip");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _ProtoCorrespDefRecip.get(idx1 ++)), "ProtoCorrespDefRecip");
            context.endElement();
        }
        while (idx3 != len3) {
            context.startElement("http://www.w3.org/2001/ProtocolSummarySchema", "ProtoCorrespRecipients");
            int idx_14 = idx3;
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _ProtoCorrespRecipients.get(idx_14 ++)), "ProtoCorrespRecipients");
            context.endNamespaceDecls();
            int idx_15 = idx3;
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _ProtoCorrespRecipients.get(idx_15 ++)), "ProtoCorrespRecipients");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _ProtoCorrespRecipients.get(idx3 ++)), "ProtoCorrespRecipients");
            context.endElement();
        }
        while (idx4 != len4) {
            context.startElement("http://www.w3.org/2001/ProtocolSummarySchema", "ProtoCorrespTempl");
            int idx_16 = idx4;
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _ProtoCorrespTempl.get(idx_16 ++)), "ProtoCorrespTempl");
            context.endNamespaceDecls();
            int idx_17 = idx4;
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _ProtoCorrespTempl.get(idx_17 ++)), "ProtoCorrespTempl");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _ProtoCorrespTempl.get(idx4 ++)), "ProtoCorrespTempl");
            context.endElement();
        }
    }

    public void serializeAttributes(edu.mit.coeus.utils.xml.bean.protocol.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx1 = 0;
        final int len1 = ((_ProtoCorrespDefRecip == null)? 0 :_ProtoCorrespDefRecip.size());
        int idx3 = 0;
        final int len3 = ((_ProtoCorrespRecipients == null)? 0 :_ProtoCorrespRecipients.size());
        int idx4 = 0;
        final int len4 = ((_ProtoCorrespTempl == null)? 0 :_ProtoCorrespTempl.size());
        if (!has_ProtoCorrespTypeCode) {
            context.reportError(com.sun.xml.bind.serializer.Util.createMissingObjectError(this, "ProtoCorrespTypeCode"));
        }
        int idx7 = 0;
        final int len7 = ((_ProtocolCorrespondence == null)? 0 :_ProtocolCorrespondence.size());
        while (idx7 != len7) {
            idx7 += 1;
        }
        while (idx1 != len1) {
            idx1 += 1;
        }
        while (idx3 != len3) {
            idx3 += 1;
        }
        while (idx4 != len4) {
            idx4 += 1;
        }
    }

    public void serializeURIs(edu.mit.coeus.utils.xml.bean.protocol.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx1 = 0;
        final int len1 = ((_ProtoCorrespDefRecip == null)? 0 :_ProtoCorrespDefRecip.size());
        int idx3 = 0;
        final int len3 = ((_ProtoCorrespRecipients == null)? 0 :_ProtoCorrespRecipients.size());
        int idx4 = 0;
        final int len4 = ((_ProtoCorrespTempl == null)? 0 :_ProtoCorrespTempl.size());
        if (!has_ProtoCorrespTypeCode) {
            context.reportError(com.sun.xml.bind.serializer.Util.createMissingObjectError(this, "ProtoCorrespTypeCode"));
        }
        int idx7 = 0;
        final int len7 = ((_ProtocolCorrespondence == null)? 0 :_ProtocolCorrespondence.size());
        while (idx7 != len7) {
            idx7 += 1;
        }
        while (idx1 != len1) {
            idx1 += 1;
        }
        while (idx3 != len3) {
            idx3 += 1;
        }
        while (idx4 != len4) {
            idx4 += 1;
        }
    }

    public java.lang.Class getPrimaryInterface() {
        return (edu.mit.coeus.utils.xml.bean.protocol.ProtoCorrespType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000b"
+"expandedExpq\u0000~\u0000\u0002xpppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000pp"
+"sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsr\u0000\'com.sun.msv.grammar.trex.ElementPattern\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLcom/sun/msv/grammar/NameClass;xr\u0000\u001e"
+"com.sun.msv.grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclared"
+"AttributesL\u0000\fcontentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003pp\u0000sq\u0000~\u0000\u0000ppsr\u0000\u001bcom.sun.m"
+"sv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/D"
+"atatype;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLcom/sun/msv/util/StringPair"
+";xq\u0000~\u0000\u0003ppsr\u0000 com.sun.msv.datatype.xsd.IntType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000+"
+"com.sun.msv.datatype.xsd.IntegerDerivedType\u0099\u00f1]\u0090&6k\u00be\u0002\u0000\u0001L\u0000\nbas"
+"eFacetst\u0000)Lcom/sun/msv/datatype/xsd/XSDatatypeImpl;xr\u0000*com.s"
+"un.msv.datatype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun."
+"msv.datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.data"
+"type.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUrit\u0000\u0012Ljava/la"
+"ng/String;L\u0000\btypeNameq\u0000~\u0000\u001cL\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/datat"
+"ype/xsd/WhiteSpaceProcessor;xpt\u0000 http://www.w3.org/2001/XMLS"
+"chemat\u0000\u0003intsr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$"
+"Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.WhiteSpacePr"
+"ocessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u0000*com.sun.msv.datatype.xsd.MaxInclusiv"
+"eFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000#com.sun.msv.datatype.xsd.RangeFacet\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\nlimitValuet\u0000\u0012Ljava/lang/Object;xr\u00009com.sun.msv.dat"
+"atype.xsd.DataTypeWithValueConstraintFacet\"\u00a7Ro\u00ca\u00c7\u008aT\u0002\u0000\u0000xr\u0000*com"
+".sun.msv.datatype.xsd.DataTypeWithFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0005Z\u0000\fisFacet"
+"FixedZ\u0000\u0012needValueCheckFlagL\u0000\bbaseTypeq\u0000~\u0000\u0018L\u0000\fconcreteTypet\u0000\'"
+"Lcom/sun/msv/datatype/xsd/ConcreteType;L\u0000\tfacetNameq\u0000~\u0000\u001cxq\u0000~"
+"\u0000\u001bppq\u0000~\u0000#\u0000\u0001sr\u0000*com.sun.msv.datatype.xsd.MinInclusiveFacet\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000%ppq\u0000~\u0000#\u0000\u0000sr\u0000!com.sun.msv.datatype.xsd.LongType"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0017q\u0000~\u0000\u001ft\u0000\u0004longq\u0000~\u0000#sq\u0000~\u0000$ppq\u0000~\u0000#\u0000\u0001sq\u0000~\u0000+ppq\u0000~"
+"\u0000#\u0000\u0000sr\u0000$com.sun.msv.datatype.xsd.IntegerType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000"
+"\u0017q\u0000~\u0000\u001ft\u0000\u0007integerq\u0000~\u0000#sr\u0000,com.sun.msv.datatype.xsd.FractionDi"
+"gitsFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001I\u0000\u0005scalexr\u0000;com.sun.msv.datatype.xsd.Dat"
+"aTypeWithLexicalConstraintFacetT\u0090\u001c>\u001azb\u00ea\u0002\u0000\u0000xq\u0000~\u0000(ppq\u0000~\u0000#\u0001\u0000sr\u0000"
+"#com.sun.msv.datatype.xsd.NumberType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0019q\u0000~\u0000\u001ft\u0000"
+"\u0007decimalq\u0000~\u0000#q\u0000~\u00009t\u0000\u000efractionDigits\u0000\u0000\u0000\u0000q\u0000~\u00003t\u0000\fminInclusives"
+"r\u0000\u000ejava.lang.Long;\u008b\u00e4\u0090\u00cc\u008f#\u00df\u0002\u0000\u0001J\u0000\u0005valuexr\u0000\u0010java.lang.Number\u0086\u00ac\u0095\u001d"
+"\u000b\u0094\u00e0\u008b\u0002\u0000\u0000xp\u0080\u0000\u0000\u0000\u0000\u0000\u0000\u0000q\u0000~\u00003t\u0000\fmaxInclusivesq\u0000~\u0000=\u007f\u00ff\u00ff\u00ff\u00ff\u00ff\u00ff\u00ffq\u0000~\u0000.q\u0000~\u0000"
+"<sr\u0000\u0011java.lang.Integer\u0012\u00e2\u00a0\u00a4\u00f7\u0081\u00878\u0002\u0000\u0001I\u0000\u0005valuexq\u0000~\u0000>\u0080\u0000\u0000\u0000q\u0000~\u0000.q\u0000~\u0000"
+"@sq\u0000~\u0000B\u007f\u00ff\u00ff\u00ffsr\u00000com.sun.msv.grammar.Expression$NullSetExpress"
+"ion\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003ppsr\u0000\u001bcom.sun.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d"
+"\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u001cL\u0000\fnamespaceURIq\u0000~\u0000\u001cxpq\u0000~\u0000 q\u0000~\u0000\u001fsr\u0000\u001dcom"
+".sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001ppsr\u0000 com.sun.msv"
+".grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameClassq\u0000~\u0000\u000e"
+"xq\u0000~\u0000\u0003sr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psq\u0000~\u0000\u0012ppsr"
+"\u0000\"com.sun.msv.datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0019q\u0000~\u0000\u001ft\u0000"
+"\u0005QNameq\u0000~\u0000#q\u0000~\u0000Fsq\u0000~\u0000Gq\u0000~\u0000Rq\u0000~\u0000\u001fsr\u0000#com.sun.msv.grammar.Simp"
+"leNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u001cL\u0000\fnamespaceURIq\u0000~\u0000\u001cx"
+"r\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0004typet\u0000)http:"
+"//www.w3.org/2001/XMLSchema-instancesr\u00000com.sun.msv.grammar."
+"Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003sq\u0000~\u0000M\u0001psq\u0000~\u0000Tt"
+"\u0000\u0014ProtoCorrespTypeCodet\u0000,http://www.w3.org/2001/ProtocolSumm"
+"arySchemasq\u0000~\u0000\rpp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0012q\u0000~\u0000Npsr\u0000#com.sun.msv.dataty"
+"pe.xsd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxq\u0000~\u0000\u0019q\u0000~\u0000\u001ft\u0000\u0006st"
+"ringsr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Preserv"
+"e\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\"\u0001q\u0000~\u0000Fsq\u0000~\u0000Gq\u0000~\u0000dq\u0000~\u0000\u001fsq\u0000~\u0000Ippsq\u0000~\u0000Kq\u0000~\u0000Np"
+"q\u0000~\u0000Oq\u0000~\u0000Vq\u0000~\u0000Zsq\u0000~\u0000Tt\u0000\u000bDescriptionq\u0000~\u0000^sq\u0000~\u0000\rpp\u0000sq\u0000~\u0000\u0000ppsq\u0000"
+"~\u0000\u0012ppsr\u0000%com.sun.msv.datatype.xsd.DateTimeType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000"
+")com.sun.msv.datatype.xsd.DateTimeBaseType\u0014W\u001a@3\u00a5\u00b4\u00e5\u0002\u0000\u0000xq\u0000~\u0000\u0019q"
+"\u0000~\u0000\u001ft\u0000\bdateTimeq\u0000~\u0000#q\u0000~\u0000Fsq\u0000~\u0000Gq\u0000~\u0000rq\u0000~\u0000\u001fsq\u0000~\u0000Ippsq\u0000~\u0000Kq\u0000~\u0000N"
+"pq\u0000~\u0000Oq\u0000~\u0000Vq\u0000~\u0000Zsq\u0000~\u0000Tt\u0000\u000fUpdateTimestampq\u0000~\u0000^sq\u0000~\u0000\rpp\u0000sq\u0000~\u0000\u0000"
+"ppq\u0000~\u0000asq\u0000~\u0000Ippsq\u0000~\u0000Kq\u0000~\u0000Npq\u0000~\u0000Oq\u0000~\u0000Vq\u0000~\u0000Zsq\u0000~\u0000Tt\u0000\nUpdateUse"
+"rq\u0000~\u0000^sq\u0000~\u0000\rpp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000asq\u0000~\u0000Ippsq\u0000~\u0000Kq\u0000~\u0000Npq\u0000~\u0000Oq\u0000~\u0000Vq\u0000"
+"~\u0000Zsq\u0000~\u0000Tt\u0000\bModuleIdq\u0000~\u0000^sq\u0000~\u0000Ippsr\u0000 com.sun.msv.grammar.One"
+"OrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.msv.grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001"
+"\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0002xq\u0000~\u0000\u0003q\u0000~\u0000Npsq\u0000~\u0000\rq\u0000~\u0000Np\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\rpp\u0000sq\u0000~"
+"\u0000Ippsq\u0000~\u0000\u0085q\u0000~\u0000Npsq\u0000~\u0000Kq\u0000~\u0000Npsr\u00002com.sun.msv.grammar.Expressi"
+"on$AnyStringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003q\u0000~\u0000[psr\u0000 com.sun.msv"
+".grammar.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000Uq\u0000~\u0000Zsq\u0000~\u0000Tt\u0000@edu.mit."
+"coeus.utils.xml.bean.protocol.ProtocolCorrespondenceTypet\u0000+h"
+"ttp://java.sun.com/jaxb/xjc/dummy-elementssq\u0000~\u0000Ippsq\u0000~\u0000Kq\u0000~\u0000"
+"Npq\u0000~\u0000Oq\u0000~\u0000Vq\u0000~\u0000Zsq\u0000~\u0000Tt\u0000\u0016ProtocolCorrespondenceq\u0000~\u0000^q\u0000~\u0000Zsq"
+"\u0000~\u0000Ippsq\u0000~\u0000\u0085q\u0000~\u0000Npsq\u0000~\u0000\rq\u0000~\u0000Np\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\rpp\u0000sq\u0000~\u0000Ippsq\u0000~"
+"\u0000\u0085q\u0000~\u0000Npsq\u0000~\u0000Kq\u0000~\u0000Npq\u0000~\u0000\u008fq\u0000~\u0000\u0091q\u0000~\u0000Zsq\u0000~\u0000Tt\u0000>edu.mit.coeus.ut"
+"ils.xml.bean.protocol.ProtoCorrespDefRecipTypeq\u0000~\u0000\u0094sq\u0000~\u0000Ipps"
+"q\u0000~\u0000Kq\u0000~\u0000Npq\u0000~\u0000Oq\u0000~\u0000Vq\u0000~\u0000Zsq\u0000~\u0000Tt\u0000\u0014ProtoCorrespDefRecipq\u0000~\u0000^"
+"q\u0000~\u0000Zsq\u0000~\u0000Ippsq\u0000~\u0000\u0085q\u0000~\u0000Npsq\u0000~\u0000\rq\u0000~\u0000Np\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\rpp\u0000sq\u0000~\u0000"
+"Ippsq\u0000~\u0000\u0085q\u0000~\u0000Npsq\u0000~\u0000Kq\u0000~\u0000Npq\u0000~\u0000\u008fq\u0000~\u0000\u0091q\u0000~\u0000Zsq\u0000~\u0000Tt\u0000@edu.mit.c"
+"oeus.utils.xml.bean.protocol.ProtoCorrespRecipientsTypeq\u0000~\u0000\u0094"
+"sq\u0000~\u0000Ippsq\u0000~\u0000Kq\u0000~\u0000Npq\u0000~\u0000Oq\u0000~\u0000Vq\u0000~\u0000Zsq\u0000~\u0000Tt\u0000\u0016ProtoCorrespReci"
+"pientsq\u0000~\u0000^q\u0000~\u0000Zsq\u0000~\u0000Ippsq\u0000~\u0000\u0085q\u0000~\u0000Npsq\u0000~\u0000\rq\u0000~\u0000Np\u0000sq\u0000~\u0000\u0000ppsq\u0000"
+"~\u0000\rpp\u0000sq\u0000~\u0000Ippsq\u0000~\u0000\u0085q\u0000~\u0000Npsq\u0000~\u0000Kq\u0000~\u0000Npq\u0000~\u0000\u008fq\u0000~\u0000\u0091q\u0000~\u0000Zsq\u0000~\u0000Tt"
+"\u0000;edu.mit.coeus.utils.xml.bean.protocol.ProtoCorrespTemplTyp"
+"eq\u0000~\u0000\u0094sq\u0000~\u0000Ippsq\u0000~\u0000Kq\u0000~\u0000Npq\u0000~\u0000Oq\u0000~\u0000Vq\u0000~\u0000Zsq\u0000~\u0000Tt\u0000\u0011ProtoCorre"
+"spTemplq\u0000~\u0000^q\u0000~\u0000Zsr\u0000\"com.sun.msv.grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/grammar/ExpressionPool$Clos"
+"edHash;xpsr\u0000-com.sun.msv.grammar.ExpressionPool$ClosedHash\u00d7j"
+"\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstreamVersionL\u0000\u0006parentt\u0000$Lcom/sun/msv/gr"
+"ammar/ExpressionPool;xp\u0000\u0000\u0000*\u0001pq\u0000~\u0000\u0087q\u0000~\u0000\u009aq\u0000~\u0000\fq\u0000~\u0000\u00a8q\u0000~\u0000\u00b6q\u0000~\u0000\tq"
+"\u0000~\u0000\bq\u0000~\u0000\u0006q\u0000~\u0000mq\u0000~\u0000\u000bq\u0000~\u0000\u0007q\u0000~\u0000Jq\u0000~\u0000hq\u0000~\u0000tq\u0000~\u0000zq\u0000~\u0000\u0080q\u0000~\u0000\u0095q\u0000~\u0000\nq"
+"\u0000~\u0000\u00a3q\u0000~\u0000\u00b1q\u0000~\u0000\u00bfq\u0000~\u0000\u008bq\u0000~\u0000\u009eq\u0000~\u0000`q\u0000~\u0000yq\u0000~\u0000\u007fq\u0000~\u0000\u00acq\u0000~\u0000\u00baq\u0000~\u0000\u0084q\u0000~\u0000\u0099q"
+"\u0000~\u0000\u00a7q\u0000~\u0000\u00b5q\u0000~\u0000\u0005q\u0000~\u0000\u0089q\u0000~\u0000\u009cq\u0000~\u0000\u00aaq\u0000~\u0000\u00b8q\u0000~\u0000\u008cq\u0000~\u0000\u009fq\u0000~\u0000\u00adq\u0000~\u0000\u00bbq\u0000~\u0000\u0011x"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends edu.mit.coeus.utils.xml.bean.protocol.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(edu.mit.coeus.utils.xml.bean.protocol.impl.runtime.UnmarshallingContext context) {
            super(context, "----------------------------");
        }

        protected Unmarshaller(edu.mit.coeus.utils.xml.bean.protocol.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return edu.mit.coeus.utils.xml.bean.protocol.impl.ProtoCorrespTypeImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  15 :
                        if (("ProtocolCorrespondence" == ___local)&&("http://www.w3.org/2001/ProtocolSummarySchema" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 16;
                            return ;
                        }
                        state = 18;
                        continue outer;
                    case  19 :
                        if (("ProtoCorrespTypeCode" == ___local)&&("http://www.w3.org/2001/ProtocolSummarySchema" == ___uri)) {
                            _getProtoCorrespDefRecip().add(((edu.mit.coeus.utils.xml.bean.protocol.impl.ProtoCorrespDefRecipTypeImpl) spawnChildFromEnterElement((edu.mit.coeus.utils.xml.bean.protocol.impl.ProtoCorrespDefRecipTypeImpl.class), 20, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        break;
                    case  3 :
                        if (("Description" == ___local)&&("http://www.w3.org/2001/ProtocolSummarySchema" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 4;
                            return ;
                        }
                        break;
                    case  24 :
                        if (("ProtoCorrespRecipients" == ___local)&&("http://www.w3.org/2001/ProtocolSummarySchema" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 22;
                            return ;
                        }
                        if (("ProtoCorrespTempl" == ___local)&&("http://www.w3.org/2001/ProtocolSummarySchema" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 25;
                            return ;
                        }
                        state = 27;
                        continue outer;
                    case  25 :
                        if (("ProtoCorrespTypeCode" == ___local)&&("http://www.w3.org/2001/ProtocolSummarySchema" == ___uri)) {
                            _getProtoCorrespTempl().add(((edu.mit.coeus.utils.xml.bean.protocol.impl.ProtoCorrespTemplTypeImpl) spawnChildFromEnterElement((edu.mit.coeus.utils.xml.bean.protocol.impl.ProtoCorrespTemplTypeImpl.class), 26, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        break;
                    case  27 :
                        if (("ProtoCorrespTempl" == ___local)&&("http://www.w3.org/2001/ProtocolSummarySchema" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 25;
                            return ;
                        }
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  9 :
                        if (("UpdateUser" == ___local)&&("http://www.w3.org/2001/ProtocolSummarySchema" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 10;
                            return ;
                        }
                        break;
                    case  6 :
                        if (("UpdateTimestamp" == ___local)&&("http://www.w3.org/2001/ProtocolSummarySchema" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 7;
                            return ;
                        }
                        break;
                    case  21 :
                        if (("ProtoCorrespDefRecip" == ___local)&&("http://www.w3.org/2001/ProtocolSummarySchema" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 19;
                            return ;
                        }
                        if (("ProtoCorrespRecipients" == ___local)&&("http://www.w3.org/2001/ProtocolSummarySchema" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 22;
                            return ;
                        }
                        state = 24;
                        continue outer;
                    case  22 :
                        if (("ProtocolNumber" == ___local)&&("http://www.w3.org/2001/ProtocolSummarySchema" == ___uri)) {
                            _getProtoCorrespRecipients().add(((edu.mit.coeus.utils.xml.bean.protocol.impl.ProtoCorrespRecipientsTypeImpl) spawnChildFromEnterElement((edu.mit.coeus.utils.xml.bean.protocol.impl.ProtoCorrespRecipientsTypeImpl.class), 23, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        break;
                    case  0 :
                        if (("ProtoCorrespTypeCode" == ___local)&&("http://www.w3.org/2001/ProtocolSummarySchema" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 1;
                            return ;
                        }
                        break;
                    case  12 :
                        if (("ModuleId" == ___local)&&("http://www.w3.org/2001/ProtocolSummarySchema" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 13;
                            return ;
                        }
                        break;
                    case  18 :
                        if (("ProtocolCorrespondence" == ___local)&&("http://www.w3.org/2001/ProtocolSummarySchema" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 16;
                            return ;
                        }
                        if (("ProtoCorrespDefRecip" == ___local)&&("http://www.w3.org/2001/ProtocolSummarySchema" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 19;
                            return ;
                        }
                        state = 21;
                        continue outer;
                    case  16 :
                        if (("FinalFlag" == ___local)&&("http://www.w3.org/2001/ProtocolSummarySchema" == ___uri)) {
                            _getProtocolCorrespondence().add(((edu.mit.coeus.utils.xml.bean.protocol.impl.ProtocolCorrespondenceTypeImpl) spawnChildFromEnterElement((edu.mit.coeus.utils.xml.bean.protocol.impl.ProtocolCorrespondenceTypeImpl.class), 17, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        break;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  15 :
                        state = 18;
                        continue outer;
                    case  5 :
                        if (("Description" == ___local)&&("http://www.w3.org/2001/ProtocolSummarySchema" == ___uri)) {
                            context.popAttributes();
                            state = 6;
                            return ;
                        }
                        break;
                    case  2 :
                        if (("ProtoCorrespTypeCode" == ___local)&&("http://www.w3.org/2001/ProtocolSummarySchema" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  26 :
                        if (("ProtoCorrespTempl" == ___local)&&("http://www.w3.org/2001/ProtocolSummarySchema" == ___uri)) {
                            context.popAttributes();
                            state = 27;
                            return ;
                        }
                        break;
                    case  17 :
                        if (("ProtocolCorrespondence" == ___local)&&("http://www.w3.org/2001/ProtocolSummarySchema" == ___uri)) {
                            context.popAttributes();
                            state = 18;
                            return ;
                        }
                        break;
                    case  24 :
                        state = 27;
                        continue outer;
                    case  20 :
                        if (("ProtoCorrespDefRecip" == ___local)&&("http://www.w3.org/2001/ProtocolSummarySchema" == ___uri)) {
                            context.popAttributes();
                            state = 21;
                            return ;
                        }
                        break;
                    case  23 :
                        if (("ProtoCorrespRecipients" == ___local)&&("http://www.w3.org/2001/ProtocolSummarySchema" == ___uri)) {
                            context.popAttributes();
                            state = 24;
                            return ;
                        }
                        break;
                    case  27 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  14 :
                        if (("ModuleId" == ___local)&&("http://www.w3.org/2001/ProtocolSummarySchema" == ___uri)) {
                            context.popAttributes();
                            state = 15;
                            return ;
                        }
                        break;
                    case  21 :
                        state = 24;
                        continue outer;
                    case  11 :
                        if (("UpdateUser" == ___local)&&("http://www.w3.org/2001/ProtocolSummarySchema" == ___uri)) {
                            context.popAttributes();
                            state = 12;
                            return ;
                        }
                        break;
                    case  18 :
                        state = 21;
                        continue outer;
                    case  8 :
                        if (("UpdateTimestamp" == ___local)&&("http://www.w3.org/2001/ProtocolSummarySchema" == ___uri)) {
                            context.popAttributes();
                            state = 9;
                            return ;
                        }
                        break;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  15 :
                        state = 18;
                        continue outer;
                    case  24 :
                        state = 27;
                        continue outer;
                    case  27 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  21 :
                        state = 24;
                        continue outer;
                    case  18 :
                        state = 21;
                        continue outer;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  15 :
                        state = 18;
                        continue outer;
                    case  24 :
                        state = 27;
                        continue outer;
                    case  27 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  21 :
                        state = 24;
                        continue outer;
                    case  18 :
                        state = 21;
                        continue outer;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  15 :
                            state = 18;
                            continue outer;
                        case  24 :
                            state = 27;
                            continue outer;
                        case  13 :
                            state = 14;
                            eatText1(value);
                            return ;
                        case  27 :
                            revertToParentFromText(value);
                            return ;
                        case  4 :
                            state = 5;
                            eatText2(value);
                            return ;
                        case  21 :
                            state = 24;
                            continue outer;
                        case  1 :
                            state = 2;
                            eatText3(value);
                            return ;
                        case  10 :
                            state = 11;
                            eatText4(value);
                            return ;
                        case  18 :
                            state = 21;
                            continue outer;
                        case  7 :
                            state = 8;
                            eatText5(value);
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

        private void eatText1(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _ModuleId = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText2(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Description = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText3(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _ProtoCorrespTypeCode = javax.xml.bind.DatatypeConverter.parseInt(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                has_ProtoCorrespTypeCode = true;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText4(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _UpdateUser = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText5(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _UpdateTimestamp = ((java.util.Calendar) com.sun.msv.datatype.xsd.DateTimeType.theInstance.createJavaObject(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value), null));
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

    }

}
