//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.27 at 09:21:38 AM IST 
//

package edu.mit.coeus.xml.instprop.impl.runtime;

public interface PrefixCallback
{
    void onPrefixMapping( String prefix, String uri ) throws org.xml.sax.SAXException;
}
